var DEFAULT_PARAMS = {

/**
 * CONSTANTS
 */
NUMBER_OF_CELLS: 20,
SIM_DURATION: 5000,
UPDATE_PERIOD: 5,
INITIAL_POPULATION: 100,
CELL_DIMENSION: 1010 / NUMBER_OF_CELLS,
AGENT_DIMENSION: CELL_DIMENSION/4,
AGENT_COLOR: "red",
GENE_COUNT: 5,
BIOLOGICAL_GENOME_LABEL: 0,
INDIVIDUAL_LEARNING_LABEL: 1,
SOCIAL_LEARNING_LABEL: 2,

/**
 * VARIABLES TO VARY
 */

// VARS AFFECTING REPRODUCTION AND MORTALITY
MAX_BONUS: 10,
BONUS_DISTRIBUTION_RANDOM: true,
BONUS_DISTRIBUTION_INCREASE_LEFT: false,
BONUS_DISTRIBUTION_INCREASE_RIGHT: false,
BONUS_DISTRIBUTION_INCREASE_CENTER: false,
BONUS_DISTRIBUTION_DECREASE_CENTER: false,
BONUS_DISTRIBUTION_PLATEAU: false,
BONUS_DISTRIBUTION_PEAKS_AND_TROUGHS: false,

DEATH_CHANCE: 0.01,
WORLD_DIFFICULTY: 8,
REPRODUCTION_FACTOR: 6,
REPRODUCTION_BASE_COST: 10,
REPRODUCTION_START_AGE: 12,
REPRODUCTION_END_AGE: 25, 
CELLPOP_PENALTY_FACTOR: 25,

// VARS EFFECTING LEARNING
BIOLOGICAL_LEARNING: true,
B_GENOME_MUTATION_RATE: 0.05,

INDIVIDUAL_LEARNING: true,
I_GENOME_MUTATION_RATE: 0.05,
IL_RATE: 1,

SOCIAL_LEARNING_ENVIRONMENT_CELL: true, // CELLS
SOCIAL_LEARNING_ENVIRONMENT_WORLD: false, // ENTIRE WORLD
SOCIAL_LEARNING_OPTIMUM_AGENT: true,
SOCIAL_LEARNING_RAND_AGENT: true,
SOCIAL_LEARNING: true,
S_GENOME_MUTATION_RATE: 0.05,
SL_RATE: 1

}


// - env. bonus
// -learning rates
// -social learning range
// -reproduction cost 


